Misp 1266 fix licensing
Ultimaker/libCharon pull request #30
Opened 2021-04-13 21:54 UTC by shanx

2021-04-14 08:24 UTC, robinmdh requested changes
I'd suggest leaving in the LGPL v3 remarks.
because https://github.com/Ultimaker/libCharon/blob/master/LICENSE

2021-04-14 13:09 UTC, shanx commented
Yeah I agree! Thanks for being sharp

2021-04-15 05:35 UTC, CoenSchalkwijk commented
Yes, can confirm too (repo is already open and marked as LGPL), BUT still suggest to remove the AGPL reference: this addition is both unintentional and collides with the LGPL ref. @shanx

2021-04-15 12:13 UTC, CoenSchalkwijk approved these changes

2021-04-15 13:30 UTC, robinmdh approved these changes

2021-04-16 05:53 UTC, merged